### ISSUE TITLE
Stretched view on learn page and github badge page

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#244]
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/d69bc3a7-c8fa-4e2f-a0d2-69bdd14add74">

This view work fine on the desktop monitor view.

**Comment by nishant0708** [comment]
Hey @sanjay-kv can I try it

**Comment by sanjay-kv** [comment]
![image](https://github.comser-attachments/assets/43eee64f-1683-4f18-9045-8b3b4baa3265)

@nishant0708 @Ayushmaanagarwal1211

**Comment by nishant0708** [comment]
hey @sanjay-kv sir i have a query Can you please Clarify the Currency of the price money.
![image](https://github.com/user-attachments/assets/363ffbad-c2e3-45d7-a3e7-fbffe6f8b8a6)
because here you used emoji of Euros. below you wrote dollar  and everyone is saying it is rupees so its bit confusing . It would be really grate if can clarify  this thanks .

**Comment by sanjay-kv** [comment]
its in rupees.
