### ISSUE TITLE
Issue regarding Upadation of readme having correct setup procedure.

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#683]
### Discussed in https://github.com/recodehive/awesome-github-profiles/discussions/677

<div type='discussions-op-text'>

<sup>Originally posted by **MuKulsoop** October  8, 2024</sup>
As the code is in the gh-pages branch. Can a issue be raised regarding updating the readme file having proper steps for the setup of the project in the local environment. 
Like using command "git clone --branch gh-pages https://github.com/Username/awesome-github-profiles.git" to clone the code in the local environment ( for beginners ).</div>

**Comment by vprathap21** [comment]
I'd like to do it. Can you assign it to me?

**Comment by yehiarasheed** [comment]
I can do this issue can you assign me for it

**Comment by Techbarsha** [comment]
Could you please assign me the task of updating the README with setup instructions.. I’ll include steps like using(demo) attractively:
`git clone --branch gh-pages https://github.com/Username/awesome-github-profiles.git`
also explain details about setup procedure
please assign  @sanjay-kv

**Comment by yehiarasheed** [comment]
Just for clarity @sanjay-kv, you would like to change the steps in the README.md file on the `main` branch so that beginners can directly clone the working branch aka the `gh-pages` branch and start working on it right away with a command like `git clone --branch gh-pages https://github.com/Username/awesome-github-profiles.git` right?
