### ISSUE TITLE
Add a detailed add_your_repo.md on how to add profile

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#74]
You can name the readme as `add_your_repo.md`
any video explanation would be great. 

+ newbie might have problem getting the long ss, so stress that part as well. 
+ many people are still not using category tag properly so we can mention that as well.

**Comment by nishant0708** [comment]
Hey @sanjay-kv can I work on it?

**Comment by nishant0708** [comment]
hey @sanjay-kv sir Actually i think Category Tag is Not working . Because it is not getting stored

**Comment by nishant0708** [comment]
hey @sanjay-kv sir so to make category storage automatic would take bit of a time because we are looking for script which would help in our case but we are trying to make it super easy 
![Screenshot 2024-08-06 081136](https://github.com/user-attachments/assets/77f0631c-c0d9-4745-969d-a0b7ebe29e3e)
![Screenshot 2024-08-06 081158](https://github.com/user-attachments/assets/ab654bf1-52bd-4867-98da-8b7de614bad7)
 
 
 But as i mention i will take some time because @dinxsh and me are looking for solution of this. So should i Complete this above task with Current info and as soon as i complete this task i will update md file as well..

**Comment by sanjay-kv** [comment]
its okay if we cant add autmatic, the above manual check box will do.

**Comment by nishant0708** [comment]
Actually @sanjay-kv the thing is when user type command "all-contributors ....." then all contributor bot add details of user in .all-contributorsrc  but User will select their Categories in the issue itself so we need some way to retrived checkedboxes and  store it in .all-contributorsrc  . else it will not work 

Or What Contibutor Can do is DO that Manually (But It will be bit complex)



https://github.com/user-attachments/assets/fb355832-01a0-4e5d-9b5d-23bb9ed83dd2

**Comment by sanjay-kv** [comment]
we cant trust the contributor on this, there will be people who mess things always. i will also see what we can do here.
