### ISSUE TITLE
Sticky icon  Change

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/awesome-github-profiles#911]
![image](https://github.com/user-attachments/assets/a358bdf3-f57a-425f-a961-09881aca122d)

rearrange the icone. 

Github should go on top. facebook should be down. 

and replace facebook link with https://www.facebook.com/sanjay.k.viswanathan/

**Comment by Akshithsaai** [comment]
@sanjay-kv I would Like to work on this issue.

**Comment by Akshithsaai** [comment]
@sanjay-kv 

I have changed the order of icons , I have tried implementing Twitter. I see that issue is already assigned so I will **not** push that change of twitter logo.
Also I have changed Facebook link as you suggested. 

Please suggest me any more changes. 

![Screenshot 2024-10-18 134626](https://github.com/user-attachments/assets/78097b8f-7ffd-4af3-873c-4b4fb5279c3e)
